version: "3.9"
services:
  local-db:
    image: "registry.hub.docker.com/library/postgres:14.2-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    profiles:
      - dev
  local-adminer:
    image: "registry.hub.docker.com/library/adminer"
    ports:
      - "6080:8080"
    restart: always
    profiles:
      - dev
